export const resultsHeaderText = [
    "Oh look what I found!",
    "Here's a good one for you!",
    "I'm sure you're gonna like this!",
    "Hey, check this out!",
    "This is a good one!",
    "I've never seen this one!",
    "Do you like this one?",
    "This is one my faves!",
    "The search Gods gave you this!",
    "Here's an interesting one!",
    "This one's a classic!",
    "This one's a gem!",
    "A movie just for you!",   
    "It's movie time!",  
    "I've got a surprise for you!",
    "I have a feeling you'll love this!", 
    "This is a must-see!", 
    "Let's watch this!",
    "You hit the jackpot!",  
    "Movie night just got better!",
    "Get your popcorn ready!", 
    "This movie is a treat!", 
    "You won't be disappointed!",
    "I found a great one for you!", 
    "This one's a winner!", 
    "Your movie is here!", 
    "Let's give this one a shot!", 
    "Don't miss this one!", 
    "Looking for a good movie?", 
    "This one's on me!",
    "It's showtime!",
    "You're gonna love this one!", 
    "This movie is a gem!",  
    "I think you'll really enjoy this one!", 
    "I've got just the thing!",  
    "This is a movie you can't miss!",
    "You're in for a treat!"
  ];